[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configuration pour le SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuration des en-têtes pour la sécurité et la performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.supabase.co; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://*.supabase.co https://images.pexels.com https://afriqueitnews.com https://www.leparisien.fr https://www.afrique-sur7.fr https://mir-s3-cdn-cf.behance.net https://www.afro-impact.com https://gozem.co https://www.goafricaonline.com https://github.com https://*.githubusercontent.com https://*.googleusercontent.com https://*.unsplash.com https://*.cdninstagram.com https://*.fbcdn.net https://*.twimg.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://fonts.googleapis.com https://fonts.gstatic.com;"

# Configuration spécifique pour les assets statiques
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
